### ISSUE TITLE
version of joblib?

### ISSUE THREAD

**Issue by Devoe-97** [ubc-vision/image-matching-benchmark#38]
I have installed joblib=1.0.1 in pyhon3.6, but when  I run run.py in python3.6, 'ImportError' is still there. 

Validating method 1/1: "sp_sg"
['phototourism', 'pragueparks', 'googleurban']
Running: phototourism, stereo track
Running: phototourism, multiview track
Running: pragueparks, stereo track
Running: pragueparks, multiview track
Running: googleurban, stereo track
Running: googleurban, multiview track
Validating key "config_phototourism_stereo"
Validating key "config_phototourism_multiview"
Validating key "config_pragueparks_stereo"
Validating key "config_pragueparks_multiview"
Validating key "config_googleurban_stereo"
Validating key "config_googleurban_multiview"
Working on sp_sg: phototourism/reichstag
 -- File feature already exists
 -- Computing match
WARNING: ./jobs/9efa086bd2840045bf66679f8d8ad4a21a0d23201b45937cb4c741cf8aa6e00d already exists!
Traceback (most recent call last):
  File "compute_match.py", line 19, in <module>
    from joblib import Parallel, delayed
ImportError: No module named joblib
Traceback (most recent call last):
  File "run.py", line 280, in <module>
    main(cfg)
  File "run.py", line 219, in main
    job_dict)
  File "run.py", line 47, in create_eval_jobs
    job = create_and_queue_jobs(cmd_list, cfg, dep_str)
  File "/cephfs/person/dihehuang/imc-2021-submit/image-matching-benchmark/utils/queue_helper.py", line 310, in create_and_queue_jobs
    cpu=cpu)
  File "/cephfs/person/dihehuang/imc-2021-submit/image-matching-benchmark/utils/queue_helper.py", line 161, in queue_job
    raise RuntimeError('Subprocess error!')
RuntimeError: Subprocess error!

**Comment by etrulls** [comment]
That's probably an error in the job itself, not joblib. Check logs/9efa086bd2840045bf66679f8d8ad4a21a0d23201b45937cb4c741cf8aa6e00d.log or, easier, just re-run the pipeline with the `--run_mode=interactive` flag to figure out why it's crashing.

**Comment by Devoe-97** [comment]
> That's probably an error in the job itself, not joblib. Check logs/9efa086bd2840045bf66679f8d8ad4a21a0d23201b45937cb4c741cf8aa6e00d.log or, easier, just re-run the pipeline with the `--run_mode=interactive` flag to figure out why it's crashing.

I have set '--run_mode=interactive', but there is no log file in ./logs
when I set sys.path.append('/usr/local/lib/python3.6/site-packages') 
it occurs: 

Traceback (most recent call last):
  File "compute_match.py", line 20, in <module>
    from joblib import Parallel, delayed
  File "/usr/local/lib/python3.6/site-packages/joblib/__init__.py", line 113, in <module>
    from .memory import Memory, MemorizedResult, register_store_backend
  File "/usr/local/lib/python3.6/site-packages/joblib/memory.py", line 274
    raise new_exc from exc
                     ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "run.py", line 281, in <module>
    main(cfg)
  File "run.py", line 220, in main
    job_dict)
  File "run.py", line 48, in create_eval_jobs
    job = create_and_queue_jobs(cmd_list, cfg, dep_str)
  File "/cephfs/person/dihehuang/imc-2021-submit/image-matching-benchmark/utils/queue_helper.py", line 310, in create_and_queue_jobs
    cpu=cpu)
  File "/cephfs/person/dihehuang/imc-2021-submit/image-matching-benchmark/utils/queue_helper.py", line 161, in queue_job
    raise RuntimeError('Subprocess error!')
RuntimeError: Subprocess error!

**Comment by etrulls** [comment]
Oh, I see your error message was indeed related to joblib, my bad. I presume this also happens when you import the library from the REPL? It's not a benchmark issue, and it's impossible for us to diagnose it. I would try installing joblib in a new conda environment and if that works, install the rest of the dependencies while ignoring library versions.

(Also: the logs only show up if you use `--run_mode=batch`, if you set it to interactive, you see error messages in the terminal.)
